package initwizard

import (
	"bytes"
	"encoding/json"
	"strings"
	"testing"
)

func TestGenerateDockSnippet_IncludesBinaryPath(t *testing.T) {
	path := "/usr/local/bin/cmux-board"
	snippet := GenerateDockSnippet(path, "")
	if !strings.Contains(snippet, path) {
		t.Errorf("expected snippet to contain binary path %q, got:\n%s", path, snippet)
	}
	// command field should end with " dock"
	if !strings.Contains(snippet, path+" dock") {
		t.Errorf("expected snippet to contain %q, got:\n%s", path+" dock", snippet)
	}
}

func TestGenerateDockSnippet_VersionComment(t *testing.T) {
	snippet := GenerateDockSnippet("/usr/local/bin/cmux-board", "0.64.7")
	if !strings.Contains(snippet, "0.64.7") {
		t.Errorf("expected version 0.64.7 in snippet, got:\n%s", snippet)
	}
	if !strings.Contains(snippet, "Re-run cmux-board init") {
		t.Errorf("expected regeneration hint in snippet, got:\n%s", snippet)
	}
}

func TestGenerateDockSnippet_EmptyVersion(t *testing.T) {
	snippet := GenerateDockSnippet("/usr/local/bin/cmux-board", "")
	if strings.Contains(snippet, "Generated by") {
		t.Errorf("expected no version comment when version is empty, got:\n%s", snippet)
	}
}

func TestGenerateDockSnippet_ValidJSON(t *testing.T) {
	snippet := GenerateDockSnippet("/usr/local/bin/cmux-board", "")
	// Extract only the JSON part (before any comment lines)
	lines := strings.Split(snippet, "\n")
	var jsonLines []string
	for _, l := range lines {
		trimmed := strings.TrimSpace(l)
		if strings.HasPrefix(trimmed, "//") {
			break
		}
		jsonLines = append(jsonLines, l)
	}
	jsonPart := strings.Join(jsonLines, "\n")
	var raw json.RawMessage
	if err := json.Unmarshal([]byte(jsonPart), &raw); err != nil {
		t.Errorf("GenerateDockSnippet returned invalid JSON: %v\nSnippet:\n%s", err, jsonPart)
	}
}

func TestGenerateDockSnippet_Snapshot(t *testing.T) {
	got := GenerateDockSnippet("/usr/local/bin/cmux-board", "0.64.7")
	// Verify structure
	if !strings.Contains(got, `"type": "program"`) {
		t.Errorf("expected type=program in snippet, got:\n%s", got)
	}
	if !strings.Contains(got, `"title": "cmux-board"`) {
		t.Errorf("expected title=cmux-board in snippet, got:\n%s", got)
	}
	if !strings.Contains(got, `"width": 80`) {
		t.Errorf("expected width=80 in snippet, got:\n%s", got)
	}
}

func TestPrintDockSnippet_NonEmpty(t *testing.T) {
	var buf bytes.Buffer
	PrintDockSnippet(&buf, "/home/user/.config/cmux-board")
	out := buf.String()
	if len(out) == 0 {
		t.Error("PrintDockSnippet produced empty output")
	}
	if !strings.Contains(out, "cmux-board") {
		t.Errorf("expected 'cmux-board' in output, got:\n%s", out)
	}
	if !strings.Contains(out, "dock.json") {
		t.Errorf("expected 'dock.json' hint in output, got:\n%s", out)
	}
}

func TestPrintDockSnippet_ContainsConfigDir(t *testing.T) {
	var buf bytes.Buffer
	configDir := "/home/user/.config/cmux-board"
	PrintDockSnippet(&buf, configDir)
	out := buf.String()
	// The binary path is derived from configDir
	if !strings.Contains(out, configDir) {
		t.Errorf("expected configDir %q to appear in output, got:\n%s", configDir, out)
	}
}
