package initwizard

// NOTE: The dock.json schema was not verified against `cmux docs dock` because that
// subcommand was unavailable or returned generic help during the T-068 spike (2026-05-27).
// The snippet below is a hand-written best-effort template. Verify against:
//
//	cmux docs dock
//
// before shipping. Tracked as PLAN_REVIEW RT-2.
//
// Known-working fallback shape for cmux dock.json (right-sidebar array entry):
//
//	{
//	  "type": "program",
//	  "command": "<binaryPath> dock",
//	  "width": 80,
//	  "title": "cmux-board"
//	}

import (
	"encoding/json"
	"fmt"
	"io"
	"path/filepath"
)

// dockSnippetFields is the canonical shape of a cmux dock.json entry for cmux-board.
// Fields are derived from the known-working cmux dock panel schema (see testdata/dock_docs.txt).
type dockSnippetFields struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Width   int    `json:"width"`
	Title   string `json:"title"`
}

// GenerateDockSnippet returns the minimal dock.json fragment the user should paste into
// ~/.config/cmux/dock.json to register cmux-board as a right-sidebar dock control.
// binaryPath is the absolute path to the cmux-board binary (printed by init wizard).
// cmuxVersion is the cmux version string; if empty, the version comment is omitted.
func GenerateDockSnippet(binaryPath string, cmuxVersion string) string {
	fields := dockSnippetFields{
		Type:    "program",
		Command: binaryPath + " dock",
		Width:   80,
		Title:   "cmux-board",
	}
	data, err := json.MarshalIndent(fields, "", "  ")
	if err != nil {
		// Should never happen with a static struct; return a safe fallback.
		return fmt.Sprintf(`{"type":"program","command":%q,"width":80,"title":"cmux-board"}`, binaryPath+" dock")
	}
	snippet := string(data)
	if cmuxVersion != "" {
		snippet += "\n// Generated by cmux-board init for cmux " + cmuxVersion
		snippet += "\n// Re-run cmux-board init to regenerate if cmux dock schema changes."
	}
	return snippet
}

// PrintDockSnippet writes a human-readable block containing the JSON snippet the user
// should add to ~/.config/cmux/dock.json to register cmux-board as a Dock panel.
// configDir is the path to ~/.config/cmux-board/ (used to embed the absolute binary path).
func PrintDockSnippet(w io.Writer, configDir string) {
	binaryPath := filepath.Join(configDir, "..", "cmux-board")
	// Use the absolute resolved binary hint based on configDir.
	snippet := GenerateDockSnippet(binaryPath, "")
	fmt.Fprintln(w, "--- Add this to ~/.config/cmux/dock.json ---")
	fmt.Fprintln(w, snippet)
	fmt.Fprintln(w, "--------------------------------------------")
}
